#!/bin/bash
# Daily Human Nature Entry Generator & Committer
# Called by OpenClaw automation each day

set -e
REPO_DIR="/home/itsaddyon/.openclaw/workspace/main/human-nature"
cd "$REPO_DIR"

# Today's date info
DATE=$(date +%Y-%m-%d)
DAY_NUM=$(date +%j)
ENTRY_FILE="entries/${DATE}.json"

mkdir -p entries

# Note: The actual entry content is generated by Ishita in a separate agent run
# This script just commits whatever new files exist

# Add any new files
git add entries/ index.html 2>/dev/null || git add .

# Check if there's anything to commit
if git diff --staged --quiet; then
  echo "No changes to commit"
  exit 0
fi

# Get current observation count from index.html for commit message
COMMIT_MSG="Day ${DAY_NUM}: Daily human nature observation — ${DATE}"

git commit -m "$COMMIT_MSG"
git push origin master

echo "✅ Committed: $COMMIT_MSG"
